aspire:  
  webdriver:
     scope: 
      
  jbehave:
    metat-data:
    thread: 1
    story-time-out: 3000 
    rerun: 0
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
          #- stories/barneys/**.story
          - stories/bcbg/**.story
          - stories/bergdorf/**.story
          - stories/ebags/**.story
          - stories/eddiebauer/**.story
          - stories/gilt/**.story
          #- stories/harrods/**.story
          - stories/herroom/**.story
          - stories/hisroom/**.story
          #- stories/landsend/**.story
          #- stories/lanebryant/**.story
          - stories/lastcall/**.story
          - stories/llbean/**.story
          - stories/lordandtaylor/**.story 
          - stories/neimanmarcus/**.story
          - stories/pacsun/**.story
          - stories/ruelala/**.story
          - stories/saks/**.story
          - stories/saksoff/**.story
          #- stories/sephora/**.story
          - stories/underarmour/**.story
          
          
                    
          
          

  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/

spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: ERROR
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0







   