aspire:  
  webdriver:
     scope: 
   
   
  dashboard:
     integration:
      enabled: true
      host: 82.212.71.230
      port: 5080
      path: api
      protocol: http
      logLevel: 
      projectId: 
      
  jbehave:
    metat-data:
    thread: 1
    story-time-out: 3000 
    rerun: 0 
    softassert: 
      enabled: true 
    stories:
      defaultloader:
        enabled: true   
        include: 
           - stories/saks/TC**.story
          #- 
          
          
          
     
          
        
  screenshot:
    enabled: true
    only-on-failure: true
    filesaver:
      enabled: true
      folder-location: ./screenshots/

spring:
  output:
    ansi:
      enabled: always  
logging:
  level: 
    com:
      aspire: DEBUG
  file: application_zurqan.log  


endpoints:
  beans:
    sensitive: false
  shutdown:
    enabled: true
  env:
    sensitive: false
    
    
server:
  port: 0







   